version: '3'
services:
  my_nginx:
    image: obzen/my-nginx:1.0
    ports:
      - 80:8080
    volumes:
      - ./content:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - my_php  
  my_php:
    image: php:7.2-fpm 
    volumes:
      - ./content:/var/www/html
  
